### ISSUE TITLE
Bookmark: Layers aren´t marked as activate in legend

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#989]
**Describe the bug**
When using a saved bookmark the layers aren´t always activated properly. The layer is shown in the map but is not activated in the legend. This seems to effect layers with sublayers.

**To Reproduce**

1. Create a bookmark with at least one layer containing sublayers.
2. Reload map.
3. Choose the newly created bookmark.
4. Confirm that the correct layer is activated and the map moved.
5. Check the legend and it looks like the activated layer is not active.

**Expected behavior**
The layer should be marked as activate in the legend

**Screenshots**
![image](https://user-images.githubusercontent.com/38069156/151148461-f513c596-f50a-46e7-847f-6e7a23c85e21.png)

**Comment by jesade-vbg** [comment]
I can't recreate this issue. Maybe the problem was solved in #990 ?

**Comment by WCarlsson** [comment]
I´ve checked out and tested develop and the problem still seems to be present. 
It also appears when a layer with sublayers is activated and the bookmark is supposed to deactivate it. The layer is then not visible in the map but it looks like it is activated in the legend.
